# Generated by Django 5.0.6 on 2024-05-14 23:55

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_userprofile_birth_date_alter_userprofile_cv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=Users.models.user_profile_pic_directory_path),
        ),
    ]
