# Generated by Django 5.0.6 on 2024-05-09 11:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('temporary', 'Temporary')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=255)),
                ('requirements', models.TextField()),
                ('role', models.CharField(max_length=255)),
                ('card_color', models.CharField(max_length=7)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='Company.companyprofile')),
            ],
        ),
    ]
